from Evolutionary_trees import Alignment, Leaf, BinNode, BinTree, Reconstruct_History

sequences=['MEVKKTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV',
'ADVKRGNISKEEEDIIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSRQ',
'DLKRGNFTADEDDLIVKLHSLLGNKWSLIAARLPGRTDNEIKNYWNTHVRRK',
'NVNKGNFTEQEEDLIIRLHKLLGNRWSLIAKRVPGRTDNQVKNYWNTHLSKK',
'DLKRGCFSQQEEDHIVALHQILGNRWSQIASHLPGRTDNEIKNFWNSCIKKK',
'DLKRGIFSEAEENLILDLHATLGNRWSRIAAQLPGRTDNEIKNYWNTRLKKR',
'SHPTYSEMIAAAIRAEKSRGGSSRQSIQKYIKSHYKVGHNADLQIKLSIRRLLAAGV',
'SHPKYSDMIASALESLKEKKGSSRQAILKYVKANFTVGDNANVHIKQALKRGVTSGQ',
'AHPSSSEMVLAAITALKERGGSSAQAIRKYIEKNYTVDIKKQAIFIKRALITGVEKGT',
'THPPTSVMVMAAIKALKERNGSSLPAIKKYIAANYKVDVVKNAHFIKKALKSLVEKKK',
'KPSTLSMIVAAITAMKNRKGSSVQAIRKYILANNKGINTSHLGSAMKLAFAKGLKSGV',
'AHPPVIDMITAAIAAQKERRGSSVAKIQSYIAAKYRCDINALNPHIRRALKNQVKSGA',
'AHPPYINTIKEAIKQLKDRKGASKQAILKFISQNYKLGDNVIQINAHHRQALKRGV',
'AHPPVATMVVTAILGLKERKGSSMVAIKKYIAANYRVDVARLAPFIRKFIRKA',
'SHPTYEEMIKDAIVTLKERTGSSQYAIQKFIEEKRKELPPTFRKLLLLNLKRLVASGK',
'NHPTYQVMISTAIAHYKDRTGSSQPAIIKYIEANYNVAPDTFKTQLKLALKRLVAKGT',
'MRSSAKQEELVKAFKALLKEEKFSSQGEIVAALQEQGFDNINQSKVSRMLTKFGAVRT',
'MARHRRIVDILNRQPVRSQSQLAKLLADNGLSVTQATLSRDLDELGAVKI',
'ENLNPVTRTARQALILQILDKQKVTSQVQLSELLLDEGIDITQATLSRDLDELGARKV',
'MNKGQRHIKIREIITSNEIETQDELVDMLKQDGYKVTQATVSRDIKELHLVKV',
'MNKGQRHIKIREIIMSNDIETQDELVDRLREAGFNVTQATVSRDIKEMQLVKV',
'MRKRDRHQLIKKMITEEKLSTQKEIQDRLEAHNVCVTQTTLSRDLREIGLTKV',
'GPEVAANRAGRQARIVAILSSAQVRSQNELAALLAAEGIEVTQATLSRDLEELGAVKL',
'TPDEREALGTRVRIIEELLRGEMSQRELKNELGAGIATITRGSNSLKAAPV',
'TADERDAVGLRLQIVSQLIDKNMPQREIQQNLNTSAATITRGSNMIKTMDP',
'SFSERKDVASRYHIIRALLEGELTQREIAEKYGVSIAQITRGSNALKGLDP',
'RGSALSDTERAQLDVMKLLNVSLHEMSRKISRSRHCIRVYLKDPVSYGT']

print 'Making alignment for:', sequences[:2]
score,(aligned_sequence1, aligned_sequence2)= Alignment(sequences[0],sequences[1])
print 'Alignment score:', score
print 'Alignment:'
print aligned_sequence1
print aligned_sequence2
print

t= BinTree(BinNode(BinNode(Leaf(sequences[0]),Leaf(sequences[1])),BinNode(Leaf(sequences[2]),BinNode(Leaf(sequences[3]),Leaf(sequences[4])))))
print 'Tree t:'
print t
print 'The evolutionary cost for a tree without designated ancestor sequences is', t.history_cost()
print

t.reconstruct_ancestors()
print 'Tree t with designated ancestor sequences:'
print t
print 'The evolutionary cost of a tree t:', t.history_cost()
print

print 'Reconstructing the tree for the sequences', sequences
t= Reconstruct_History(sequences)
print t
print 'The evolutionary cost of the reconstructed tree:', t.history_cost()



#ANSWER:
# Making alignment for: ['MEVKKTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV', 'ADVKRGNISKEEEDIIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSRQ']
# Alignment score: 26
# Alignment:
# MEVK_KTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV
# ADVKRGNISKEEED_IIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSR_Q
#
# Tree t:
#   █>
#   ├-█>
#   │ ├-MEVKKTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV
#   │ └-ADVKRGNISKEEEDIIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSRQ
#   └-█>
#     ├-DLKRGNFTADEDDLIVKLHSLLGNKWSLIAARLPGRTDNEIKNYWNTHVRRK
#     └-█>
#       ├-NVNKGNFTEQEEDLIIRLHKLLGNRWSLIAKRVPGRTDNQVKNYWNTHLSKK
#       └-DLKRGCFSQQEEDHIVALHQILGNRWSQIASHLPGRTDNEIKNFWNSCIKKK
# The evolutionary cost for a tree without designated ancestor sequences is None
#
# Tree t with designated ancestor sequences:
#   █>DVKRGNFSKEEDDRIIYKLHALLGNRWSQIASRLPGRTDNQIKNHWNSHMIRKQ
#   ├-█>ADVKRKNSSKEEEDRIIYKAHARLGNRWSLIAKLLPGRTDNEIKNHWNSHMRRKQ
#   │ ├-MEVKKTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV
#   │ └-ADVKRGNISKEEEDIIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSRQ
#   └-█>DLKKGNFSADEDDHIIKLHSLLGNKWSQIASRLPGRTDNQIKNYWNSHIRKK
#     ├-DLKRGNFTADEDDLIVKLHSLLGNKWSLIAARLPGRTDNEIKNYWNTHVRRK
#     └-█>DLKKGCFSQQEEDHIIRLHKILGNRWSQIASRLPGRTDNQIKNYWNSHIKKK
#       ├-NVNKGNFTEQEEDLIIRLHKLLGNRWSLIAKRVPGRTDNQVKNYWNTHLSKK
#       └-DLKRGCFSQQEEDHIVALHQILGNRWSQIASHLPGRTDNEIKNFWNSCIKKK
# The evolutionary cost of a tree t: 90
#
# Reconstructing the tree for the sequences ['MEVKKTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV', 'ADVKRGNISKEEEDIIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSRQ', 'DLKRGNFTADEDDLIVKLHSLLGNKWSLIAARLPGRTDNEIKNYWNTHVRRK', 'NVNKGNFTEQEEDLIIRLHKLLGNRWSLIAKRVPGRTDNQVKNYWNTHLSKK', 'DLKRGCFSQQEEDHIVALHQILGNRWSQIASHLPGRTDNEIKNFWNSCIKKK', 'DLKRGIFSEAEENLILDLHATLGNRWSRIAAQLPGRTDNEIKNYWNTRLKKR', 'SHPTYSEMIAAAIRAEKSRGGSSRQSIQKYIKSHYKVGHNADLQIKLSIRRLLAAGV', 'SHPKYSDMIASALESLKEKKGSSRQAILKYVKANFTVGDNANVHIKQALKRGVTSGQ', 'AHPSSSEMVLAAITALKERGGSSAQAIRKYIEKNYTVDIKKQAIFIKRALITGVEKGT', 'THPPTSVMVMAAIKALKERNGSSLPAIKKYIAANYKVDVVKNAHFIKKALKSLVEKKK', 'KPSTLSMIVAAITAMKNRKGSSVQAIRKYILANNKGINTSHLGSAMKLAFAKGLKSGV', 'AHPPVIDMITAAIAAQKERRGSSVAKIQSYIAAKYRCDINALNPHIRRALKNQVKSGA', 'AHPPYINTIKEAIKQLKDRKGASKQAILKFISQNYKLGDNVIQINAHHRQALKRGV', 'AHPPVATMVVTAILGLKERKGSSMVAIKKYIAANYRVDVARLAPFIRKFIRKA', 'SHPTYEEMIKDAIVTLKERTGSSQYAIQKFIEEKRKELPPTFRKLLLLNLKRLVASGK', 'NHPTYQVMISTAIAHYKDRTGSSQPAIIKYIEANYNVAPDTFKTQLKLALKRLVAKGT', 'MRSSAKQEELVKAFKALLKEEKFSSQGEIVAALQEQGFDNINQSKVSRMLTKFGAVRT', 'MARHRRIVDILNRQPVRSQSQLAKLLADNGLSVTQATLSRDLDELGAVKI', 'ENLNPVTRTARQALILQILDKQKVTSQVQLSELLLDEGIDITQATLSRDLDELGARKV', 'MNKGQRHIKIREIITSNEIETQDELVDMLKQDGYKVTQATVSRDIKELHLVKV', 'MNKGQRHIKIREIIMSNDIETQDELVDRLREAGFNVTQATVSRDIKEMQLVKV', 'MRKRDRHQLIKKMITEEKLSTQKEIQDRLEAHNVCVTQTTLSRDLREIGLTKV', 'GPEVAANRAGRQARIVAILSSAQVRSQNELAALLAAEGIEVTQATLSRDLEELGAVKL', 'TPDEREALGTRVRIIEELLRGEMSQRELKNELGAGIATITRGSNSLKAAPV', 'TADERDAVGLRLQIVSQLIDKNMPQREIQQNLNTSAATITRGSNMIKTMDP', 'SFSERKDVASRYHIIRALLEGELTQREIAEKYGVSIAQITRGSNALKGLDP', 'RGSALSDTERAQLDVMKLLNVSLHEMSRKISRSRHCIRVYLKDPVSYGT']
#   █>EMNRSDAKQEDLKVRKALIEESVTSRREYAEKKNAPGVIIVQVKNMLEEFGTVK
#   ├-█>SYSMEKADLTVRKNLILESVEKRRKYIEKKNRPGAIIVQLKNNLVSIGTDK
#   │ ├-█>RPSYISMEAAALTVMKNLKGSSVEMIRKYIEKKNRVGIIVHLKKNLVSGT
#   │ │ ├-█>AKPSYISMIAAAITTMKNRKGSSVQAIQKYIEKKNNVGINIQHLMKHRRAKNLVSGT
#   │ │ │ ├-█>AHPSYIDMIAEAITTQKERKGSSMPAIQKYIEKKYRVDINIQNLFHRRANLVSGT
#   │ │ │ │ ├-█>AHPTYINMIAEAIATLKDRTGSSKQAIQKYIKSHYKLPHNNIQLKLNHRRALASGT
#   │ │ │ │ │ ├-█>SHPTYEVMIATAIATLKDRTGSSRQAIQKYIKSHYKELPHNFNKQLKLNLRRGVASGT
#   │ │ │ │ │ │ ├-█>SHPTYSDMIASALRSLKSKKGSSRQAIQKYIKSHFKVGHNANVQIKLSLRRGVASGQ
#   │ │ │ │ │ │ │ ├-SHPKYSDMIASALESLKEKKGSSRQAILKYVKANFTVGDNANVHIKQALKRGVTSGQ
#   │ │ │ │ │ │ │ └-SHPTYSEMIAAAIRAEKSRGGSSRQSIQKYIKSHYKVGHNADLQIKLSIRRLLAAGV
#   │ │ │ │ │ │ └-█>NHPTYEVMIKTAIATYKDRTGSSQPAIQKFIEANYKELPPTFKKLLLLNLKRLVASGT
#   │ │ │ │ │ │   ├-NHPTYQVMISTAIAHYKDRTGSSQPAIIKYIEANYNVAPDTFKTQLKLALKRLVAKGT
#   │ │ │ │ │ │   └-SHPTYEEMIKDAIVTLKERTGSSQYAIQKFIEEKRKELPPTFRKLLLLNLKRLVASGK
#   │ │ │ │ │ └-AHPPYINTIKEAIKQLKDRKGASKQAILKFISQNYKLGDNVIQINAHHRQALKRGV
#   │ │ │ │ └-█>AHPSVIDMILAAITAQKERKGSSMPKIQSYIEKKYRVDINRQNPFIRRANIVSGK
#   │ │ │ │   ├-█>AHPSTAEMVLAAITALKERKGSSMPAIKKYIEKNYRVDVARQAPFIKRAFIVRKK
#   │ │ │ │   │ ├-█>AHPSTSEMVLAAITALKERNGSSAPAIKKYIEKNYTVDVVKQAHFIKRALISLVEKGK
#   │ │ │ │   │ │ ├-THPPTSVMVMAAIKALKERNGSSLPAIKKYIAANYKVDVVKNAHFIKKALKSLVEKKK
#   │ │ │ │   │ │ └-AHPSSSEMVLAAITALKERGGSSAQAIRKYIEKNYTVDIKKQAIFIKRALITGVEKGT
#   │ │ │ │   │ └-AHPPVATMVVTAILGLKERKGSSMVAIKKYIAANYRVDVARLAPFIRKFIRKA
#   │ │ │ │   └-AHPPVIDMITAAIAAQKERRGSSVAKIQSYIAAKYRCDINALNPHIRRALKNQVKSGA
#   │ │ │ └-KPSTLSMIVAAITAMKNRKGSSVQAIRKYILANNKGINTSHLGSAMKLAFAKGLKSGV
#   │ │ └-RGSALSDTERAQLDVMKLLNVSLHEMSRKISRSRHCIRVYLKDPVSYGT
#   │ └-█>SEVNKGDFTSREDIILEQLEKRLGNRELAKNLPGAGIAQIKNGWNSIHTRDK
#   │   ├-█>SPDERDDVGSRYHIIEELLEKELTQRELAENLGAGIAQITRGSNMIKTLDP
#   │   │ ├-█>TPDERDAVGLRLRIVEELLDKNMPQRELKQNLNAGIATITRGSNMIKTMPP
#   │   │ │ ├-TADERDAVGLRLQIVSQLIDKNMPQREIQQNLNTSAATITRGSNMIKTMDP
#   │   │ │ └-TPDEREALGTRVRIIEELLRGEMSQRELKNELGAGIATITRGSNSLKAAPV
#   │   │ └-SFSERKDVASRYHIIRALLEGELTQREIAEKYGVSIAQITRGSNALKGLDP
#   │   └-█>MEVNKGSFTEEEDLILYQLHKRLGNRWSEIAKRLPGRTDNAIKNHWNSTHRRKK
#   │     ├-█>DVNKGNFSEAEEDLIIKLHALLGNRWSRIAKRLPGRTDNEIKNYWNTHLSKK
#   │     │ ├-█>DLKRGNFSEAEEDNLIIKLHATLGNKWSRIASRLPGRTDNEIKNYWNTHISKR
#   │     │ │ ├-█>ADLKRGNISAEEDDLIIKLHATLGNKWSLIASRLPGRTDNEIKNYWNSHVSRK
#   │     │ │ │ ├-DLKRGNFTADEDDLIVKLHSLLGNKWSLIAARLPGRTDNEIKNYWNTHVRRK
#   │     │ │ │ └-ADVKRGNISKEEEDIIIKLHATLGNRWSLIASHLPGRTDNEIKNYWNSHLSRQ
#   │     │ │ └-█>DLKRGIFSEAEENLIVDLHQILGNRWSRIASHLPGRTDNEIKNYWNTCIKKR
#   │     │ │   ├-DLKRGIFSEAEENLILDLHATLGNRWSRIAAQLPGRTDNEIKNYWNTRLKKR
#   │     │ │   └-DLKRGCFSQQEEDHIVALHQILGNRWSQIASHLPGRTDNEIKNFWNSCIKKK
#   │     │ └-NVNKGNFTEQEEDLIIRLHKLLGNRWSLIAKRVPGRTDNQVKNYWNTHLSKK
#   │     └-MEVKKTSWTEEEDRILYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKV
#   └-█>EMNRSDAKQEELVKAFKALTKEEKVTSQGEIADLQAAEGVNINQATVSRMLEEFGAVKV
#     ├-█>EMANKGDAHQALIRKQITSKELVTSQNEIADLLAAEGVNVTQATLSRDIEELGAVKV
#     │ ├-█>EMANPRTAHQALIVQILSKAQVTSQNQLAKLLAAEGLSITQATLSRDLEELGAVKV
#     │ │ ├-█>PMANRAHRARIVDILSRAQVRSQNELAKLLAAEGLSVTQATLSRDLEELGAVKI
#     │ │ │ ├-GPEVAANRAGRQARIVAILSSAQVRSQNELAALLAAEGIEVTQATLSRDLEELGAVKL
#     │ │ │ └-MARHRRIVDILNRQPVRSQSQLAKLLADNGLSVTQATLSRDLDELGAVKI
#     │ │ └-ENLNPVTRTARQALILQILDKQKVTSQVQLSELLLDEGIDITQATLSRDLDELGARKV
#     │ └-█>MRKGDRHQLIRKMITSEELETQKEIVDRLEQHGVNVTQATLSRDIREMGLTKV
#     │   ├-█>MNKGQRHIKIREIITSNEIETQDELVDRLRQAGYNVTQATVSRDIKEMHLVKV
#     │   │ ├-MNKGQRHIKIREIIMSNDIETQDELVDRLREAGFNVTQATVSRDIKEMQLVKV
#     │   │ └-MNKGQRHIKIREIITSNEIETQDELVDMLKQDGYKVTQATVSRDIKELHLVKV
#     │   └-MRKRDRHQLIKKMITEEKLSTQKEIQDRLEAHNVCVTQTTLSRDLREIGLTKV
#     └-MRSSAKQEELVKAFKALLKEEKFSSQGEIVAALQEQGFDNINQSKVSRMLTKFGAVRT
# The evolutionary cost of the reconstructed tree: 776

